from arquivoBanco import ContaBancaria

print('='*40)
print('BANCO PYTHON'.center(40))
print('='*40)

conta1=ContaBancaria("Jorge", 550)
conta2=ContaBancaria("Beatriz", 400)
print('CONTA 1 - TITULAR JORGE')
conta1.depositar(100)
print('-'*40)
print('CONTA 2 - TITULAR BEATRIZ')
conta2.depositar(200)
print('-'*40)
conta1.transferir(125, conta2)
print('-'*40)
print('CONTA 1 - TITULAR JORGE')
conta1.exibir_saldo()
print('-'*40)
print('CONTA 2 - TITULAR BEATRIZ')
conta2.exibir_saldo()
print('-'*40)
print('CONTA 1 - TITULAR JORGE')
conta1.exibir_extrato()
print('-'*40)
print('CONTA 2 - TITULAR BEATRIZ')
conta2.exibir_extrato()